#!/bin/bash
##
##编译 运行c语言 
##
##参数  $1 文件
##      $2 c文件运行的参数
##      $3 编译选项
############################################
if [ $# -eq 3 ]; then
    gcc $1 $3
else
    gcc $1
fi

if [ $? != 0 ]; then
    exit 1
fi

if [ $# -ge 2 ]; then
    ./a.out $2
else
    ./a.out
fi


